"""PEP格式固定常量 — 跨机场不变, 直接硬编码"""

# TXT顶层
VERSION = 1
STATE = "CHINA"

# QFU级固定值
ENTRY_ANGLE = 180
GROOVED_PFC_SURFACE_TO = "False"
GROOVED_PFC_STOPWAY = "False"
RUNWAY_PAVEMENT = 1
GROOVED_PFC_SURFACE_LD = "False"
SPD_OPTI_FLAG = 0
MAX_GA_KVS = "1.23"
MAX_ACC_DIST = 0
CLB_SPEED_LIMIT = "True"
INITIAL_CLB_SPEED = 250
SPEED_LIMIT_ALT = "3048.00003767014"

# GAMethodFlag=0 (有ILS)时的固定配套值
APPROACH_SLOPE = "2.5"
INCREMENT_GA_HEIGHT = "457.2"
GLIDE_SLOPE = "-3"

# 英尺/米换算
FT_TO_M = 0.3048
M_TO_FT = 3.28084

# XLSX "跑道数据"页 D 列公式系数
ROUNDUP_FT_FACTOR = 3.28084

# 几何: ICAO 起飞航径保护区
PROTECTION_BASE_WIDTH = 90        # 起点半宽(m)
PROTECTION_SLOPE = 0.125          # 扩展斜率
PROTECTION_FULL_DIST = 6480       # 封顶距离(m)
PROTECTION_MAX_WIDTH = 900        # 封顶半宽(m)

# 1.2%梯度面
GRADIENT_SURFACE = 0.012
